---
- name: Install extra packages
  apt:
    name: '{{ item }}'
    state: latest
  with_items: '{{ server.packages }}'
  when: server.packages is defined

- name: Configure the timezone
  template:
    src: timezone
    dest: /etc/timezone

- name: Configure the timezone
  file:
    src: '/usr/share/zoneinfo/{{ server.timezone }}'
    dest: /etc/localtime
    state: link
    force: yes

- name: Set default system language pack
  locale_gen:
    name: '{{ server.locale }}'
    state: present

- include: swap.yml
- include: links.yml
