---
- name: Install apache
  apt:
    name: apache2
    state: latest

- name: Enable apache modules
  apache2_module:
    name: '{{ item }}'
    state: present
  notify: Restart apache
  with_items: '{{ apache.modules }}'

- name: Add ServerName to apache.conf
  lineinfile:
    dest: /etc/apache2/apache2.conf
    state: present
    line: 'ServerName localhost'

- name: Change default apache site
  template:
    src: vhost.conf
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart apache
