imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    # Sonata conf
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_doctrine_orm_admin.yml }
    # FOS conf
    - { resource: fos/fos_user.yml }

parameters:
    locale: en

framework:
    translator:
        fallback: %locale%
    secret: %secret%
    router:
        resource: %kernel.root_dir%/config/routing.yml
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    templating:
        engines: ['twig']
    default_locale: %locale%
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: %kernel.debug%
    strict_variables: %kernel.debug%
    form_themes:
           - SonataMediaBundle:Form:media_widgets.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        server_version: 5.6
        host: %database_host%
        port: %database_port%
        dbname: %database_name%
        user: %database_user%
        password: %database_password%
        charset: UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host: %mailer_host%
    username: %mailer_user%
    password: %mailer_password%
    spool:
        type: memory
