imports:
    - { resource: parameters.yml }
    # Basic
    - { resource: basic/security.yml }
    - { resource: basic/doctrine.yml }
    - { resource: basic/swiftmailer.yml }
    - { resource: basic/twig.yml }
    # Sonata conf
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_doctrine_orm_admin.yml }
    - { resource: sonata/sonata_formatter.yml }
    # FOS conf
    - { resource: fos/fos_user.yml }

parameters:
    locale: en

framework:
    translator:
        fallback: %locale%
    secret: %secret%
    router:
        resource: %kernel.root_dir%/config/routing.yml
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    templating:
        engines: ['twig']
    default_locale: %locale%
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        handler_id: ~
    fragments: ~
    http_method_override: true
