---
server:
  packages: [vim, git]
  timezone: Europe/Madrid
  locale: es_ES.UTF-8
vagrant_local:
  hostname: default
apache:
  docroot: /vagrant/web
  servername: sonata.dev
  serveralias: ''
mysql:
  root_password: root
  database: sonata
  user: sonata
  password: sonata
  dump: ''
php:
  ppa: php5-5.6
  packages: [php5-cli, php5-intl, php5-mcrypt, php5-xdebug, php5-curl, php5-mysql, php5-sqlite, php5-apcu, php5-gd]
symfony:
  secret: c81e356a07607848a59e492f824b3fc3bbe61542
