---
- name: Create symfony files
  become: false
  template:
    src: '{{ item }}'
    dest: '/tmp/{{ item }}'
  with_items:
    - parameters.yml

- name: Move symfony files
  become: false
  command: 'cp /tmp/{{ item.file }} {{ item.dest }}/{{ item.file }}'
  with_items:
    - { file: parameters.yml, dest: /vagrant/app/config }

- include: permissions.yml
