---
- name: Create parameters.yml
  template:
    src: parameters.yml
    dest: /vagrant/app/config/parameters.yml

- name: Create .htaccess
  template:
    src: .htaccess
    dest: /vagrant/web/.htaccess
