---
- name: Create parameters.yml
  template:
    src: parameters.yml
    dest: /vagrant/app/config/parameters.yml

- name: Create .htaccess
  template:
    src: .htaccess
    dest: /vagrant/web/.htaccess

- name: Create app_dev.php
  template:
    src: app_dev.php
    dest: /vagrant/web/app_dev.php
