---
- name: Set the hostname in /etc/hostname
  shell: echo {{ vagrant_local.hostname }} > /etc/hostname

- name: Set the hostname
  shell: hostname {{ vagrant_local.hostname }}

- name: Update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 localhost {{ vagrant_local.hostname }}'
    owner: root
    group: root
    mode: '0644'

- name: Open on /vagrant by default
  become: false
  lineinfile:
    dest: /home/vagrant/.bashrc
    state: present
    line: 'cd /vagrant'
