---
- name: Add ppa repository
  apt_repository:
    repo: ppa:tuxpoldo/phpmyadmin

- name: Update apt
  apt:
    update_cache: yes

- name: Install phpMyAdmin
  apt:
    pkg: phpmyadmin
    state: latest

- name: Add phpMyAdmin to Apache
  lineinfile:
    dest: /etc/apache2/apache2.conf
    state: present
    line: 'Include /etc/phpmyadmin/apache.conf'
  notify: Restart Apache
