- name: Download Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer

- name: Install Composer
  shell: php /tmp/composer-installer --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Install Composer globals
  shell: composer global require {{ item }}
  with_items: '{{ composer.packages }}'
  when: composer.packages is defined
  become: false
